### ISSUE TITLE
[Doc] Debugging instructions

### ISSUE THREAD

**Issue by bbros-dev** [Nukesor/webhook-server#14]
Would help to have debug/log volume instructions documented.

**Comment by Nukesor** [comment]
What exactly do you mean by that :)?

**Comment by bbros-dev** [comment]
How does one get a log showing the data flow through 'stages' of the webhook-server.  Relevant 'stages' being those that are affected by user configuration options. Example, the co-ordination of the name the webhook-server expects and the url path that was passed in, etc. etc.
